### ISSUE TITLE
389ds didn't run on openshift

### ISSUE THREAD

**Issue by ghost** [389ds/389-ds-base#4879]
**Issue Description**
The 389ds image can not start on openshift.

**Package Version and Platform:**
 - Platform: openshift (OS: opensuse leap 15.3)
 - Package and version: 389-ds-1.4.4.14~git0.37dc95673-1.1.x86_64

docker file:
```
FROM opensuse/leap:15.3

EXPOSE 3389 3636

RUN zypper install -y 389-ds timezone openssl

RUN mkdir -p /data/config && \
    mkdir -p /data/ssca && \
    mkdir -p /data/run && \
    mkdir -p /var/run/dirsrv && \
    ln -s /data/config /etc/dirsrv/slapd-localhost && \
    ln -s /data/ssca /etc/dirsrv/ssca && \
    ln -s /data/run /var/run/dirsrv

VOLUME /data

HEALTHCHECK --start-period=5m --timeout=5s --interval=5s --retries=2 \
    CMD /usr/lib/dirsrv/dscontainer -H

CMD [ "/usr/lib/dirsrv/dscontainer", "-r" ]
```

I build the image and it run just fine on my local docker. When I push the image to openshift, the starting script stuck and failed with this log:
![image](https://user-images.githubusercontent.com/42483897/130061950-a606f6b2-6529-493d-ba30-e069d845c111.png)

We just need to run a 389ds instance for testing. Is it currently possible to run 389ds on openshift?

**Comment by vashirov** [comment]
It is possible to run it on OpenShift. 
Could you please post the full log?

**Comment by Fubuchi** [comment]
Here is the full log:
[ldap-389ds-2.log](https://github.com/389ds/389-ds-base/files/7014637/ldap-389ds-2.log)

**Comment by vashirov** [comment]
I suspect that `dscontainer` and lib389 are missing a few fixes that are present in 2.0.x version, but I couldn't reproduce the error with your Dockerfile. Could you please also share your Deployment or DeploymentConfig yamls? Do you use any SCCs? Service accounts?
Thanks.

**Comment by Fubuchi** [comment]
Here is the DeploymentConfig, for one-time deploy service, we often copy the yml directly from openshift between service so there maybe redundant information. I also try with 389ds 2.0.x from opensuse tumbleweed but the result is the same. 
```
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: ldap-389ds
  name: ldap-389ds
  namespace: #######
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: ldap-389ds
    deploymentconfig: ldap-389ds
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: ldap-389ds
        deploymentconfig: ldap-389ds
    spec:
      containers:
        - env:
            - name: DS_DM_PASSWORD
              value: ####
          image: >-
            ##########
          imagePullPolicy: Always
          name: ldap-389ds
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: artifactory
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange

```

I am not sure about SCC or service account, I need to check with our openshift team later.

**Comment by vashirov** [comment]
What exactly 2.0.x version have you tried? There was a [change](https://github.com/389ds/389-ds-base/commit/da522d5359594976d525efe52b825361356d3d6f) recently. When it's present, the error output of `ns-slapd` is shown on startup of `dscontainer`. It would be good to capture it, so we can troubleshoot further.

If it's not in the version that you tried, you can use the latest `dscontainer` in your Dockerfile:
```
ADD https://raw.githubusercontent.com/389ds/389-ds-base/master/src/lib389/cli/dscontainer /usr/lib/dirsrv/dscontainer
RUN chmod 755 /usr/lib/dirsrv/dscontainer
```
Could you please try capture the logs with the change above?

Regarding SCCs and service accounts. 
`ns-slapd` runs under `dirsrv` user, rpm package creates directories that are owned by this user. So your Pod needs to run under this user too. This can be done using service account with anyuid SCC. I.e. 

```
$ oc create serviceaccount dirsrv-sa
$ oc adm policy add-scc-to-user anyuid -n YOUR_NAMESPACE -z dirsrv-sa
```
And update your Pod spec to use `serviceAccountName: dirsrv-sa`

Also, if it's not a throwaway LDAP server, and you care about your data, I suggest to use StatefulSet instead of DeploymentConfig, as it was designed for stateful apps like LDAP server. It provides guarantees about the ordering and uniqueness of the Pods.

**Comment by Fubuchi** [comment]
The 2.0.x version is 2.0.6 from opensuse tumbleweed repo. I replace the dscontainer with the one you suggest but the log is the same: 
[ldap-389ds-4.log](https://github.com/389ds/389-ds-base/files/7019724/ldap-389ds-4.log)

Regarding SCC, I am asking the devops team to help to set up the user. I will give you feedback soon.

**Comment by vashirov** [comment]
It's strange that the log is the same. Can you try to replace CMD in your Dockerfile with `/bin/sh`, rebuild the image, start the container, then `oc rsh your_pod` and run `dscontainer` manually? Does it hang for a minute when it tries to run `ns-slapd`?

> However currently, my pod are running under root user, isn't it sufficient?

It's only mapped to root inside the container, but from the host it uses a different uid. 
If you run `oc describe` on your project, you can see uid mapping:
```
$ oc describe project ldap-389ds  | grep uid-range
                        openshift.io/sa.scc.uid-range=1000640000/10000
```

See https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids

**Comment by Fubuchi** [comment]
It is weekend now so I can not investigate further.
However, I tried to deploy with minishift on my local ldaptop with the original dockerfile and this deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-389ds-deployment
  labels:
    app: ldap-389ds
spec:
  selector:
    matchLabels:
      app: ldap-389ds
  template:
    metadata:
      labels:
        app: ldap-389ds
    spec:
      containers:
      - name: ldap-389ds-container
        image: 172.30.1.1:5000/myproject/389ds:1.4-suse
``` 

Firstly it failed with this log:
![image](https://user-images.githubusercontent.com/42483897/130282137-062c91b0-666d-4f5e-b685-fe9ac5780263.png)

After setting up the dirsrv-sa user and updating the deployment conifg, everything work as expected. So there is a high chance that the problem is I didn't run the pod with the correct user. I will investigate further and give you more feedback on monday.
