### ISSUE TITLE
Impossible to delete leaf node with broken numSubordinates

### ISSUE THREAD

**Issue by Mstrodl** [389ds/389-ds-base#5059]
**Issue Description**
A long time ago, we had a few masters replicating to eachother. One of them, ipa01-nrh, stopped working one day and we tried to delete it but couldn't. I've inherited this issue and it looks like the master's object in LDAP still has `numSubordinates` > 0, but there aren't any actual subordinates. I've tried a few different ways to delete this including disabling `nsslapd-schemacheck`, but none of them have let me modify the `numSubordinates` and `hasSubordinates` attributes. Because of this, `ldapdelete` doesn't allow me to remove the old master because it doesn't think it's a leaf node.

**Package Version and Platform:**
 - Platform: FreeIPA, RHEL 8.5
 - Package and version: `389-ds-base.x86_64 1.4.3.23-10.module+el8.5.0+12398+47000435` and `ipa-server.x86_64 4.9.6-6.module+el8.5.0+12660+88e16a2c`
 - Browser: Chromium

**Steps to Reproduce**
1. Have a broken object with `numSubordinates` and `hasSubordinates` set to a value > 0, but with no actual subordinates:
```yaml
# ipa01-nrh.csh.rit.edu, masters, ipa, etc, csh.rit.edu
dn: cn=ipa01-nrh.csh.rit.edu,cn=masters,cn=ipa,cn=etc,dc=csh,dc=rit,dc=edu
ipaMinDomainLevel: 0
ipaMaxDomainLevel: 1
ipaReplTopoManagedSuffix: dc=csh,dc=rit,dc=edu
ipaReplTopoManagedSuffix: o=ipaca
cn: ipa01-nrh.csh.rit.edu
objectClass: top
objectClass: nsContainer
objectClass: ipaReplTopoManagedServer
objectClass: ipaConfigObject
objectClass: ipaSupportedDomainLevelConfig
hasSubordinates: TRUE
numSubordinates: 5
```
2. Try deleting it:
```
$ ldapdelete -x -D "cn=directory manager" -W "cn=ipa01-nrh.csh.rit.edu,cn=masters,cn=ipa,cn=etc,dc=csh,dc=rit,dc=edu"
Enter LDAP Password:
ldap_delete: Operation not allowed on non-leaf (66)
```
3. Try modifying `numSubordinates`:
```yaml
$ cat << EOF | ldapmodify -D "cn=directory manager" -W
> dn: cn=ipa01-nrh.csh.rit.edu,cn=masters,cn=ipa,cn=etc,dc=csh,dc=rit,dc=edu
> changetype: modify
> replace: hasSubordinates
> hasSubordinates: FALSE
> -
> replace: numSubordinates
> numSubordinates: 0
> EOF
Enter LDAP Password:
modifying entry "cn=ipa01-nrh.csh.rit.edu,cn=masters,cn=ipa,cn=etc,dc=csh,dc=rit,dc=edu"
ldap_modify: Server is unwilling to perform (53)
```

4. See error, there's no way to modify this attribute, even with `-e \!relax` or `nsslapd-schemacheck: off`

**Expected results**
There should be some way to delete an object with a broken `numSubordinates` or a way to forcibly update the value of `numSubordinates`

**Additional context**
I did a bit of digging through the code, and as far as I could tell there was no technical reason why this can't be done because replica connections are allowed to modify these attributes without issue. I've also tried manually poking the Berkeley DB at `id2entry.db` with `db_dump` and `db_load` to overwrite `numSubordinates`, but it doesn't stick once 389 starts again, presumably these values will get restored from somewhere else.
