### ISSUE TITLE
The Massive memory leaking on update operations

### ISSUE THREAD

**Issue by i-ivantsov** [389ds/389-ds-base#5755]
The Massive memory leaking on update operations are seen.

Package Version and Platform:

Platform: Debian GNU/Linux 10(buster)
Package and version: 389-ds-2.4.0~git0.87efeb2-163.2.x86_64 in docker container 389-Directory/2.4.0 B2023.116.0000

1) parallel update operations in 25 connections (read, create and delete operations are performed too);
2) ds389 server had used all available memory.

There is a diagram with memory usage collected with nmon and nmonchart: 
![memory leaks](https://user-images.githubusercontent.com/123725498/236256647-dcb8fcd4-f5a1-4452-8911-64eb8e37a7c4.jpg)

**Comment by ATokma** [comment]
In my practice of using 389ds, I also observed a massive memory leak on versions 2.2, 2.3, 2.4 with creation, modification and deletion operations. Approximately 1.000,000 operations in 6 hours process 389ds allocate 32 Gb (all memory compunter) and crash proccess (out off  memory).

**Comment by OGSmv** [comment]
I have the same problem with 389ds. During modification operations the memory grows up intensively and never be freed in future.

**Comment by vashirov** [comment]
In Fedora/RHEL we ship jemalloc and LD_PRELOAD it in systemd unit for dirsrv. In a container this is not happening:
1. Image from Docker Hub ships a different rpm that doesn't bundle jemalloc, because they have a separate jemalloc rpm, but it's not installed in that image.
2. In order to use it you also have to explicitly pass LD_PRELOAD environment variable (which I think we should do by default as we do it in Fedora/RHEL).

@ATokma and @OGSmv, could you please confirm that you see this in a container too? Or what distro/package do you use?

@i-ivantsov, could you please make a new image based on docker.io/389ds/dirsrv that also includes jemalloc package and pass `LD_PRELOAD=/usr/lib64/libjemalloc.so.2` variable to the container? Or try an image from quay.io/389ds/dirsrv and pass `LD_PRELOAD=/usr/lib64/dirsrv/lib/libjemalloc.so.2` variable?

Thanks.

**Comment by OGSmv** [comment]
> In Fedora/RHEL we ship jemalloc and LD_PRELOAD it in systemd unit for dirsrv. In a container this is not happening:
> 
> 1. Image from Docker Hub ships a different rpm that doesn't bundle jemalloc, because they have a separate jemalloc rpm, but it's not installed in that image.
> 2. In order to use it you also have to explicitly pass LD_PRELOAD environment variable (which I think we should do by default as we do it in Fedora/RHEL).
> 
> @ATokma and @OGSmv, could you please confirm that you see this in a container too? Or what distro/package do you use?
> 
> @i-ivantsov, could you please make a new image based on docker.io/389ds/dirsrv that also includes jemalloc package and pass `LD_PRELOAD=/usr/lib64/libjemalloc.so.2` variable to the container? Or try an image from quay.io/389ds/dirsrv and pass `LD_PRELOAD=/usr/lib64/dirsrv/lib/libjemalloc.so.2` variable?
> 
> Thanks.

Yes, i see this using container from docker hub.
Thank you for help!

**Comment by i-ivantsov** [comment]
Victor, thank you for reply.

I build container with libjemalloc using dockerfile:
```
FROM 389ds/dirsrv:2.4

ENV DS_DM_PASSWORD="****"

RUN zypper --non-interactive install uuid openldap2-client 
RUN zypper --non-interactive install jemalloc
RUN zypper clean

RUN mkdir -p /xxx.init

COPY ./ldap_init.sh /xxx.init
COPY ./struct.ldif /xxx.init
COPY ./schema.ldif /xxx.init
COPY ./start_ds.sh /xxx.init

CMD [ "/xxx.init/start_ds.sh" ]
```

And start it with docker_compose.yaml:
```
version: "3"

volumes:
  389ds:
    name: 389ds

services:
  xxx_ldap:
    container_name: xxx_ldap
    image: docker_xxx_ldap
    restart: always
    tty: True
    stdin_open: True
    volumes:
      - 389ds:/data
    ports:
      - 3389:3389
      - 3636:3636
    environment:
      - TZ=Europe/Moscow
      - RDOMAIN_NAME=xxx
      - RDOMAIN_EXT=net
      - LD_PRELOAD=/usr/lib64/libjemalloc.so.2
      #- DS_REINDEX=true
    networks:
      - xxx_sd_net

networks:
    xxx_sd_net:
      name: xxx_sd_net    
```

Unfortunately a memory leak has been left:
![ds389_memory](https://github.com/389ds/389-ds-base/assets/123725498/5dbaa10d-eec4-49ac-8c09-79fc66798bc7)
